# Generated by Django 4.2 on 2023-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('area_comum', models.CharField(max_length=50)),
                ('area_privativa', models.CharField(max_length=50)),
                ('area_total', models.CharField(max_length=50)),
                ('dia_vencimento_boleto', models.CharField(max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('data_inicio_contrato', models.DateTimeField()),
                ('data_fim_contrato', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
