# Generated by Django 4.2 on 2023-04-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='data_fim_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='data_inicio_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
