# Generated by Django 4.2 on 2023-04-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_condominio_data_fim_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='area_comum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='área comum'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='area_privativa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='área privativa'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='area_total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='área total'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cep',
            field=models.CharField(max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='dia_vencimento_boleto',
            field=models.CharField(max_length=2, verbose_name='Dia de vencimento da fatura'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='documento',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='País'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('fracao', models.CharField(max_length=20, verbose_name='fração')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominio.condominio')),
            ],
        ),
    ]
