# Generated by Django 4.2 on 2023-04-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
