# Generated by Django 4.2 on 2023-04-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_alter_pessoa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10),
        ),
        migrations.CreateModel(
            name='PessoaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Proprietário'), ('L', 'Locatário')], default='P', max_length=1)),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='data de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='data de fim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morador', to='condominio.pessoa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='morador', to='condominio.unidade')),
            ],
        ),
    ]
