# Generated by Django 4.2 on 2023-04-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_alter_pessoa_status_pessoaunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaunidade',
            name='tipo',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Locatário', 'Locatário')], default='Proprietário', max_length=15),
        ),
    ]
