# Generated by Django 4.2 on 2023-04-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_alter_pessoaunidade_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoaunidade',
            old_name='tipo',
            new_name='vinculo',
        ),
    ]
