# Generated by Django 4.2 on 2023-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_rename_tipo_pessoaunidade_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaunidade',
            name='data_fim',
            field=models.DateTimeField(null=True, verbose_name='data de fim'),
        ),
    ]
