# Generated by Django 4.2 on 2023-04-26 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0009_alter_pessoaunidade_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaunidade',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='condominio.pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoaunidade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moradores', to='condominio.unidade'),
        ),
    ]
