# Generated by Django 4.2 on 2023-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0010_alter_pessoaunidade_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoaunidade',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoaunidade',
            name='pessoa',
            field=models.ManyToManyField(related_name='moradores', to='condominio.pessoa'),
        ),
    ]
