# Generated by Django 4.2 on 2023-04-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0011_remove_pessoaunidade_pessoa_pessoaunidade_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoaunidade',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='pessoaunidade',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='condominio.pessoa'),
            preserve_default=False,
        ),
    ]
