# Generated by Django 4.2 on 2023-05-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0014_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='unidade',
        ),
        migrations.AddField(
            model_name='conta',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condominio.condominio'),
            preserve_default=False,
        ),
    ]
