# Generated by Django 4.2 on 2023-05-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0017_alter_conta_status_alter_pessoa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateio', models.CharField(choices=[('Fração', 'Fração'), ('Unidade', 'Unidade')], default='Fração', max_length=10)),
                ('valor', models.DecimalField(decimal_places=10, max_digits=19)),
                ('data', models.DateField(null=True)),
                ('identificao', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='condominio.condominio')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='condominio.conta')),
            ],
        ),
    ]
