# Generated by Django 4.2 on 2023-05-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0018_despesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='identificao',
            new_name='identificacao',
        ),
    ]
