# Generated by Django 4.2 on 2023-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0019_rename_identificao_despesa_identificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
