# Generated by Django 4.2 on 2023-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0020_alter_despesa_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=20)),
                ('pessoa', models.CharField(max_length=100)),
                ('vinculo', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competencia', models.CharField(max_length=15)),
                ('data_vencimento', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
