# Generated by Django 4.2 on 2023-05-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0021_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='rateio',
            field=models.CharField(choices=[('F', 'Fração'), ('U', 'Unidade')], default='F', max_length=10),
        ),
    ]
