# Generated by Django 4.2 on 2023-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0023_alter_pessoaunidade_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaunidade',
            name='vinculo',
            field=models.CharField(choices=[('Proprietário', 'P'), ('Locatário', 'L')], max_length=15),
        ),
    ]
