# Generated by Django 4.2 on 2023-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0024_alter_pessoaunidade_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='rateio',
            field=models.CharField(choices=[('Fração', 'Fração'), ('Unidade', 'Unidade')], default='Fração', max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoaunidade',
            name='vinculo',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Locatário', 'Locatário')], max_length=15),
        ),
    ]
