# Generated by Django 4.2 on 2023-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0025_alter_despesa_rateio_alter_pessoaunidade_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
