# Generated by Django 4.2 on 2023-05-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0026_alter_fatura_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='updated_at',
        ),
    ]
