# Generated by Django 4.2 on 2023-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0027_remove_fatura_created_at_remove_fatura_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
