# Generated by Django 4.2 on 2023-05-11 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0028_alter_fatura_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='competencia_ano',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='competencia_mes',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 22, 21, 39, 567896, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fatura',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas_responsavel', to='condominio.pessoa'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='condominio.unidade'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='vinculo',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Locatário', 'Locatário')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together={('unidade', 'competencia_ano', 'competencia_mes')},
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='competencia',
        ),
        migrations.CreateModel(
            name='FaturaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatura_itens', to='condominio.despesa')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='condominio.fatura')),
            ],
            options={
                'unique_together': {('fatura', 'despesa')},
            },
        ),
    ]
