# Generated by Django 4.2 on 2023-05-11 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0029_fatura_competencia_ano_fatura_competencia_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='vinculo',
        ),
        migrations.AddField(
            model_name='fatura',
            name='locatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_locatario', to='condominio.pessoa'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='faturas_proprietario', to='condominio.pessoa'),
            preserve_default=False,
        ),
    ]
