# Generated by Django 4.2 on 2023-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0031_fatura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
