# Generated by Django 4.2 on 2023-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0032_fatura_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='juro',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10, verbose_name='juro ao dia (em percentual %):'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='multa',
            field=models.DecimalField(decimal_places=2, default='2', max_digits=10, verbose_name='multa (em percentual %):'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_juro',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_multa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='dia_vencimento_boleto',
            field=models.CharField(default='10', max_length=2, verbose_name='Dia de vencimento da fatura'),
        ),
    ]
