# Generated by Django 4.2 on 2023-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0033_condominio_juro_condominio_multa_fatura_valor_juro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='juro',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10, verbose_name='juro ao dia (em percentual %):'),
        ),
    ]
