# Generated by Django 4.2 on 2023-05-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0038_alter_fatura_valor_juro_alter_fatura_valor_multa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='dia_vencimento_boleto',
            field=models.CharField(max_length=2, verbose_name='Dia de vencimento da fatura'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='juro',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='juro ao mês (%):'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='multa',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='multa (%):'),
        ),
    ]
