# Generated by Django 4.2 on 2023-05-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0039_alter_condominio_dia_vencimento_boleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='dias_atraso_pagamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
