# Generated by Django 4.2 on 2023-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0041_telefone_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='endereco',
            field=models.CharField(default=2, max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
    ]
