# Generated by Django 4.2 on 2023-06-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0042_email_endereco_alter_email_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
    ]
