# Generated by Django 4.2 on 2023-06-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0043_remove_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='condominio.unidade'),
        ),
    ]
