# Generated by Django 4.2 on 2023-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0044_despesa_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='rateio',
            field=models.CharField(blank=True, choices=[('Fração', 'Fração'), ('Unidade', 'Unidade')], default='Fração', max_length=10, null=True),
        ),
    ]
