# Generated by Django 4.2 on 2023-06-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0045_alter_despesa_rateio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='rateio',
            field=models.CharField(blank=True, choices=[('Fração', 'Fração'), ('Unidade', 'Unidade')], max_length=10, null=True),
        ),
    ]
